### PR TITLE
Rm juvenile facilities from state aggregate counts

### PR DESCRIPTION
**Pull request by hjohns12**
tiny tiny change that removes facilities with age as "juvenile"

### CODE REVIEW

**Review by erika-tyagi — CHANGES_REQUESTED** [review]
I think we should hold off on this until https://github.com/uclalawcovid19behindbars/behindbarstools/pull/96 is merged, and then update off of that version! 

And thoughts on adding a parameter for `adult_only` (or something?) and then making the filter optional? / I think it makes sense to be able to filter out youth facilities for comparisons to AP/MP, but thoughts on whether we want to include them in the state and national aggregate counts we otherwise report? (I could go either way, but the fact that we're already doing this for some states pulls me towards feelings like maybe we should...?)

**Comment by hjohns12** [comment]
Yeah, I think that it makes sense to filter out juvenile facilities for the AP/MP comparison, but add them back in for statewide/national aggregates. I was a liiiitle unclear of how to make that happen but will think more deeply about it now !

**Comment by hjohns12** [comment]
- [ ] after merging this branch (after merging #96 lol), update the diagnostics-generating script to say `adult_only = TRUE` in `calc_aggregate_counts`

**Comment by hjohns12** [comment]
@erika-tyagi @nmmarquez are you both good for me to merge this while and make the change to the diagnostics script we think through `calc_aggregate_counts` more broadly by jurisdiction?

**Comment by erika-tyagi** [comment]
> @erika-tyagi @nmmarquez are you both good for me to merge this while and make the change to the diagnostics script we think through `calc_aggregate_counts` more broadly by jurisdiction?

On second thought, I think it might actually make more sense to add the parameter to `read_scrape_data` rather than here. I think the main benefit is that we can flag youth facilities based on either (1) the `Age` variable or (2) the string `youth` showing up in the scraper ID – which seems more robust than relying on `fac_info`. Not totally committed to that, but I wouldn't mind discussing more tomorrow if that works!

**Comment by hjohns12** [comment]
Closing because of our new shiny https://github.com/uclalawcovid19behindbars/behindbarstools/blob/master/R/alt_aggregate_counts.R!

**Pull request closed without merging**
