### PR TITLE
feat: add rollling sum function

### PR DESCRIPTION
**Pull request by nmmarquez**
Added a function that takes a data frame and from a numeric column that should be cumulative adds in a rolling sum from a specified window for specified groups im not sold on the name of `rolling_sum` and happy to make any interface changes. Example of using the function below.

```
read_scrape_data(all_dates = TRUE, state = "North Carolina") %>%
    # only look at one facilty
    filter(Name == "NORTH CAROLINA CORRECTIONAL INSTITUTION FOR WOMEN") %>%
    # Specify name as the column that makes unique groups
    rolling_sum(Name) %>%
    # do the plotting thing
    ggplot(aes(
        x = Date, y = Residents.Active.Estimate, color = Name, fill = Name)) +
    geom_line(size = 1.5) +
    geom_area(alpha = .5) +
    theme_behindbars() +
    scale_color_bbdiscrete() +
    scale_fill_bbdiscrete() +
    theme(legend.position = "none") +
    labs(y = "Estimated Active Cases") +
    ggtitle("Monitoring Facility Outbreaks")
```

2a968a89-c314-4fc2-b6c9-6ca92eb72062

### CODE REVIEW

**Review by hjohns12 — CHANGES_REQUESTED** [review]
Wondering if it would be possible to reformat this so that the syntax is more like: 

`read_scrape_data() %>%
      mutate(Residents.Active.Estimate = rolling_sum(Residents.Confirmed))`

Using this format, we could recycle this function to get nDeaths from the past week

cc: @erika-tyagi

**Comment by nmmarquez** [comment]
@hjohns12 the function also requires a date but yeah I like the idea would it be alright to do something like 

```
read_scrape_data() %>% mutate(Residents.Active.Estimate = rolling_sum(Residents.Confirmed, Date))
```

**Comment by hjohns12** [comment]
I'm probably missing something here -- would the parameter in rolling_sum called `Date` just be identifying the date column in the dataset? Or are you referring to the `window` parameter?

**Comment by nmmarquez** [comment]
@hjohns12 sorry wasn't clear, yeah thinking of a new parameter which needs a vector of dates and specifying the Date column

**Comment by hjohns12** [comment]
Can you give an example of how that vector of dates would be used? I'm not clear on how that would differ from a `window` parameter. Also, does the function need the date column specified as a param if it's always referred to in the same way in our data?

**Comment by nmmarquez** [comment]
Yeah for sure, we need a dates vector because we collect data on inconsistent days so we want to be able say there is a x day window of keeping data even if we only collect data every other day or every third day or some mixture of the two. I believe we need to specify it if we want the API to work in the mutate context because `rolling_sum` as a function wouldnt know about the piping environment and cant pull from it explicitly

**Comment by hjohns12** [comment]
Ohhh so would the dates vector be a start date and end date?

**Comment by erika-tyagi** [comment]
I really like Hope's idea of being able to use this in a mutate context - that seems simpler and more versatile! And sorry, I think I initially said the opposite, my bad!  

Also, I'm running into errors running this, but I think I should be able to do so? It works with more than one value in the Name column, but haven't looked into why all of NC breaks. 
```
read_scrape_data(T, T, state = "North Carolina") %>% 
    rolling_sum(Name)

Error in seq.int(0, to0 - from, by) : 'to' must be a finite number 
```

And can we default to not print the messages showing what we're joining by? e.g. `Joining, by = c("Name", "Date")`

**Comment by nmmarquez** [comment]
@erika-tyagi @hjohns12 I made some extensive changes to the api incliding changing the name of the function to reflect the fact that what we are calculating is a rolling sum of first differences. Now the workflow looks as follows

```
read_scrape_data(all_dates = TRUE, state = "North Carolina") %>%
    #filter(Name == "NORTH CAROLINA CORRECTIONAL INSTITUTION FOR WOMEN") %>%
    group_by(Name, Jurisdiction) %>%
    mutate(Residents.Active.Est = rolling_sum(Residents.Confirmed, Date)) %>%
    ggplot(aes(
        x = Date, y = Residents.Active.Est, color = Name, fill = Name)) +
    geom_line(size = 1.5) +
    geom_area(alpha = .5) +
    theme_behindbars() +
    scale_color_bbdiscrete() +
    scale_fill_bbdiscrete() +
    theme(legend.position = "none") +
    labs(y = "Estimated Active Cases") +
    ggtitle("Monitoring Facility Outbreaks")
```
> Also, I'm running into errors running this, but I think I should be able to do so? It works with more than one value in the Name column, but haven't looked into why all of NC breaks

NC breaks because the amount of data that we have for facilities is much shorter than the window, right now I have that set to break and now have an explicit error to catch that but maybe we would prefer if it didnt break and just returned NAs

> And can we default to not print the messages showing what we're joining by? e.g. Joining, by = c("Name", "Date")

No longer an issue with the api changes

> Can you give an example of how that vector of dates would be used? I'

There is now an example in the docs of different results in the output of when using position to calculate the rolling sum vs dates

```
x <- c(1, 1, 4, 4, 7, 9)
sd <- Sys.Date()
date_x <- sd - c(10, 9, 8, 6, 4, 2)

diff_roll_sum(x, window = 2)
# returns a warning
diff_roll_sum(x, date_x, window = 2)
```

**Review by hjohns12 — APPROVED** [review]
Without testing it out at all, this looks good to me. Excited to try it out, maybe even for today's social media post!

**Comment by nmmarquez** [comment]
Added some robustness to the function which will return NAs instaed of failing on short time series, also put up an example of using the function on all facilities in NC with a group by although the plot still only shows a single facility

**Pull request merged**
